"""Initial migration

Revision ID: a54f502108b7
Revises: 
Create Date: 2026-05-15 14:14:55.874221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a54f502108b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=False),
    sa.Column('locality', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.Column('escalation_priority', sa.String(length=40), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_category'), 'complaints', ['category'], unique=False)
    op.create_index(op.f('ix_complaints_created_at'), 'complaints', ['created_at'], unique=False)
    op.create_index(op.f('ix_complaints_locality'), 'complaints', ['locality'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_table('evaluation_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('complaint_id', sa.String(length=36), nullable=True),
    sa.Column('retrieval_precision', sa.Float(), nullable=True),
    sa.Column('hallucination_risk', sa.Float(), nullable=True),
    sa.Column('response_relevance', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_logs_complaint_id'), 'evaluation_logs', ['complaint_id'], unique=False)
    op.create_table('memory_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('memory_type', sa.String(length=60), nullable=False),
    sa.Column('locality', sa.String(length=160), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('source_complaint_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_records_created_at'), 'memory_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_memory_records_locality'), 'memory_records', ['locality'], unique=False)
    op.create_index(op.f('ix_memory_records_memory_type'), 'memory_records', ['memory_type'], unique=False)
    op.create_index(op.f('ix_memory_records_source_complaint_id'), 'memory_records', ['source_complaint_id'], unique=False)
    op.create_table('agent_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(length=40), nullable=False),
    sa.Column('duplicate_ids', sa.JSON(), nullable=False),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('reasoning_trace', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_reports')
    op.drop_index(op.f('ix_memory_records_source_complaint_id'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_memory_type'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_locality'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_created_at'), table_name='memory_records')
    op.drop_table('memory_records')
    op.drop_index(op.f('ix_evaluation_logs_complaint_id'), table_name='evaluation_logs')
    op.drop_table('evaluation_logs')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_locality'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_created_at'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_category'), table_name='complaints')
    op.drop_table('complaints')
    # ### end Alembic commands ###
